Repository pyt-team/TopoNetX, pull requests merged in 2023-07, with the labels that each got.

#187 Remove unnecessary sorting before frozenset constructions
  toponetx/classes/simplicial_complex.py
Labels: refactor

#188 Extract name attribute into `Complex` superclass
  toponetx/classes/cell_complex.py
  toponetx/classes/combinatorial_complex.py
  toponetx/classes/complex.py
  toponetx/classes/simplicial_complex.py
Labels: refactor

#186 Rename transform methods from graphs to simplicial complexes
  test/transform/test_graph_to_simplicial_complex.py
  toponetx/__init__.py
  toponetx/datasets/graph.py
  toponetx/transform/graph_to_simplicial_complex.py
Labels: enhancement, refactor

#189 Add more typehints throughout the project
  test/classes/test_complex.py
  toponetx/algorithms/spectrum.py
  toponetx/classes/cell.py
  toponetx/classes/cell_complex.py
  toponetx/classes/combinatorial_complex.py
  toponetx/classes/complex.py
  toponetx/classes/hyperedge.py
  toponetx/classes/reportviews.py
  toponetx/classes/simplex.py
  toponetx/classes/simplicial_complex.py
  toponetx/read_write.py
  toponetx/utils/structure.py
Labels: refactor

#180 Addition of coauthorship dataset
  test/datasets/test_graph.py
  toponetx/datasets/coauthorship.npy
  toponetx/datasets/graph.py
Labels: enhancement

#194 Fix cell complex methods
  test/classes/test_cell_complex.py
  toponetx/classes/cell_complex.py
Labels: enhancement

#203 Improve performance of `SimplicialComplex.get_boundaries`
  test/classes/test_simplicial_complex.py
  toponetx/classes/simplicial_complex.py
Labels: refactor

#204 Some cleanup everywhere
  toponetx/classes/cell_complex.py
  toponetx/classes/combinatorial_complex.py
  toponetx/classes/reportviews.py
  toponetx/classes/simplicial_complex.py
Labels: refactor
