Repository pyt-team/TopoNetX, pull requests merged in 2024-07, with the labels that each got.

#375 nsf funding added
  README.md
Labels: documentation

#379 Minor cleanup
  test/classes/test_combinatorial_complex.py
  test/generators/test_classic_cell_complex.py
  test/generators/test_random_cell_complexes.py
  test/generators/test_random_simplicial_complexes.py
  test/readwrite/test_atomlist.py
  test/transform/test_graph_to_cell_complex.py
  toponetx/classes/colored_hypergraph.py
  toponetx/classes/combinatorial_complex.py
  toponetx/classes/simplex.py
  toponetx/datasets/__init__.py
  toponetx/generators/__init__.py
  toponetx/generators/random_simplicial_complexes.py
  toponetx/readwrite/__init__.py
  toponetx/readwrite/serialization.py
  toponetx/utils/__init__.py
  toponetx/utils/normalization.py
Labels: refactor

#380 Run tests on Python 3.12
  .github/workflows/test.yml
  test/classes/test_complex.py
Labels: enhancement

#336 A simplicial complex has dimension equal to the size of its maximal s…
  test/transform/test_graph_to_simplicial_complex.py
  toponetx/transform/graph_to_simplicial_complex.py
Labels: bug, discussion

#378 Consistent dunder methods for all complexes
  test/classes/test_cell_complex.py
  test/classes/test_colored_hypergraph.py
  test/classes/test_combinatorial_complex.py
  test/classes/test_path_complex.py
  test/classes/test_reportviews.py
  test/classes/test_simplicial_complex.py
  toponetx/classes/cell_complex.py
  toponetx/classes/colored_hypergraph.py
  toponetx/classes/combinatorial_complex.py
  toponetx/classes/complex.py
  toponetx/classes/path_complex.py
  toponetx/classes/reportviews.py
  toponetx/classes/simplicial_complex.py
Labels: bug, enhancement
